<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guest.proto

namespace Guest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Guest.AddOrderAddon</code>
 */
class AddOrderAddon extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string addonid = 1;</code>
     */
    protected $addonid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $addonid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Guest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string addonid = 1;</code>
     * @return string
     */
    public function getAddonid()
    {
        return $this->addonid;
    }

    /**
     * Generated from protobuf field <code>string addonid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddonid($var)
    {
        GPBUtil::checkString($var, True);
        $this->addonid = $var;

        return $this;
    }

}

