<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guest.proto

namespace Guest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Guest.DetailPOSAddOn</code>
 */
class DetailPOSAddOn extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string addOnId = 1;</code>
     */
    protected $addOnId = '';
    /**
     * Generated from protobuf field <code>string merchantId = 2;</code>
     */
    protected $merchantId = '';
    /**
     * Generated from protobuf field <code>string merchantName = 3;</code>
     */
    protected $merchantName = '';
    /**
     * Generated from protobuf field <code>string storeid = 4;</code>
     */
    protected $storeid = '';
    /**
     * Generated from protobuf field <code>string storeName = 5;</code>
     */
    protected $storeName = '';
    /**
     * Generated from protobuf field <code>string addOnName = 6;</code>
     */
    protected $addOnName = '';
    /**
     * Generated from protobuf field <code>string addOnDescription = 7;</code>
     */
    protected $addOnDescription = '';
    /**
     * Generated from protobuf field <code>float addOnPrice = 8;</code>
     */
    protected $addOnPrice = 0.0;
    /**
     * Generated from protobuf field <code>bool addOnIsSold = 9;</code>
     */
    protected $addOnIsSold = false;
    /**
     * Generated from protobuf field <code>bool addOnIsActive = 10;</code>
     */
    protected $addOnIsActive = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $addOnId
     *     @type string $merchantId
     *     @type string $merchantName
     *     @type string $storeid
     *     @type string $storeName
     *     @type string $addOnName
     *     @type string $addOnDescription
     *     @type float $addOnPrice
     *     @type bool $addOnIsSold
     *     @type bool $addOnIsActive
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Guest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string addOnId = 1;</code>
     * @return string
     */
    public function getAddOnId()
    {
        return $this->addOnId;
    }

    /**
     * Generated from protobuf field <code>string addOnId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddOnId($var)
    {
        GPBUtil::checkString($var, True);
        $this->addOnId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string merchantId = 2;</code>
     * @return string
     */
    public function getMerchantId()
    {
        return $this->merchantId;
    }

    /**
     * Generated from protobuf field <code>string merchantId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantId($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchantId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string merchantName = 3;</code>
     * @return string
     */
    public function getMerchantName()
    {
        return $this->merchantName;
    }

    /**
     * Generated from protobuf field <code>string merchantName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMerchantName($var)
    {
        GPBUtil::checkString($var, True);
        $this->merchantName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string storeid = 4;</code>
     * @return string
     */
    public function getStoreid()
    {
        return $this->storeid;
    }

    /**
     * Generated from protobuf field <code>string storeid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setStoreid($var)
    {
        GPBUtil::checkString($var, True);
        $this->storeid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string storeName = 5;</code>
     * @return string
     */
    public function getStoreName()
    {
        return $this->storeName;
    }

    /**
     * Generated from protobuf field <code>string storeName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStoreName($var)
    {
        GPBUtil::checkString($var, True);
        $this->storeName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string addOnName = 6;</code>
     * @return string
     */
    public function getAddOnName()
    {
        return $this->addOnName;
    }

    /**
     * Generated from protobuf field <code>string addOnName = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAddOnName($var)
    {
        GPBUtil::checkString($var, True);
        $this->addOnName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string addOnDescription = 7;</code>
     * @return string
     */
    public function getAddOnDescription()
    {
        return $this->addOnDescription;
    }

    /**
     * Generated from protobuf field <code>string addOnDescription = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAddOnDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->addOnDescription = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float addOnPrice = 8;</code>
     * @return float
     */
    public function getAddOnPrice()
    {
        return $this->addOnPrice;
    }

    /**
     * Generated from protobuf field <code>float addOnPrice = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setAddOnPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->addOnPrice = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool addOnIsSold = 9;</code>
     * @return bool
     */
    public function getAddOnIsSold()
    {
        return $this->addOnIsSold;
    }

    /**
     * Generated from protobuf field <code>bool addOnIsSold = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setAddOnIsSold($var)
    {
        GPBUtil::checkBool($var);
        $this->addOnIsSold = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool addOnIsActive = 10;</code>
     * @return bool
     */
    public function getAddOnIsActive()
    {
        return $this->addOnIsActive;
    }

    /**
     * Generated from protobuf field <code>bool addOnIsActive = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setAddOnIsActive($var)
    {
        GPBUtil::checkBool($var);
        $this->addOnIsActive = $var;

        return $this;
    }

}

