<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guest.proto

namespace Guest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * === Add Order ===
 *
 * Generated from protobuf message <code>Guest.GuestAddOrderRequest</code>
 */
class GuestAddOrderRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string sessionid = 1;</code>
     */
    protected $sessionid = '';
    /**
     * Generated from protobuf field <code>string qrcode = 2;</code>
     */
    protected $qrcode = '';
    /**
     * Generated from protobuf field <code>string type = 3;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>string menuid = 4;</code>
     */
    protected $menuid = '';
    /**
     * Generated from protobuf field <code>double amount = 5;</code>
     */
    protected $amount = 0.0;
    /**
     * Generated from protobuf field <code>repeated .Guest.AddOrderAddon addon = 6;</code>
     */
    private $addon;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sessionid
     *     @type string $qrcode
     *     @type string $type
     *     @type string $menuid
     *     @type float $amount
     *     @type array<\Guest\AddOrderAddon>|\Google\Protobuf\Internal\RepeatedField $addon
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Guest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string sessionid = 1;</code>
     * @return string
     */
    public function getSessionid()
    {
        return $this->sessionid;
    }

    /**
     * Generated from protobuf field <code>string sessionid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionid($var)
    {
        GPBUtil::checkString($var, True);
        $this->sessionid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string qrcode = 2;</code>
     * @return string
     */
    public function getQrcode()
    {
        return $this->qrcode;
    }

    /**
     * Generated from protobuf field <code>string qrcode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setQrcode($var)
    {
        GPBUtil::checkString($var, True);
        $this->qrcode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 3;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string menuid = 4;</code>
     * @return string
     */
    public function getMenuid()
    {
        return $this->menuid;
    }

    /**
     * Generated from protobuf field <code>string menuid = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMenuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->menuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 5;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Guest.AddOrderAddon addon = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddon()
    {
        return $this->addon;
    }

    /**
     * Generated from protobuf field <code>repeated .Guest.AddOrderAddon addon = 6;</code>
     * @param array<\Guest\AddOrderAddon>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddon($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Guest\AddOrderAddon::class);
        $this->addon = $arr;

        return $this;
    }

}

