<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guest.proto

namespace Guest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Guest.GuestViewOrderList2</code>
 */
class GuestViewOrderList2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string category = 2;</code>
     */
    protected $category = '';
    /**
     * Generated from protobuf field <code>string menu = 3;</code>
     */
    protected $menu = '';
    /**
     * Generated from protobuf field <code>double price = 4;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>double amount = 5;</code>
     */
    protected $amount = 0.0;
    /**
     * Generated from protobuf field <code>double subtotal = 6;</code>
     */
    protected $subtotal = 0.0;
    /**
     * Generated from protobuf field <code>repeated string addonname = 7;</code>
     */
    private $addonname;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $category
     *     @type string $menu
     *     @type float $price
     *     @type float $amount
     *     @type float $subtotal
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $addonname
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Guest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category = 2;</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>string category = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string menu = 3;</code>
     * @return string
     */
    public function getMenu()
    {
        return $this->menu;
    }

    /**
     * Generated from protobuf field <code>string menu = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMenu($var)
    {
        GPBUtil::checkString($var, True);
        $this->menu = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price = 4;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>double price = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 5;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double subtotal = 6;</code>
     * @return float
     */
    public function getSubtotal()
    {
        return $this->subtotal;
    }

    /**
     * Generated from protobuf field <code>double subtotal = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setSubtotal($var)
    {
        GPBUtil::checkDouble($var);
        $this->subtotal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string addonname = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddonname()
    {
        return $this->addonname;
    }

    /**
     * Generated from protobuf field <code>repeated string addonname = 7;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddonname($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->addonname = $arr;

        return $this;
    }

}

