<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guest.proto

namespace Guest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Guest.GuestMenuByIDList</code>
 */
class GuestMenuByIDList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string menuid = 1;</code>
     */
    protected $menuid = '';
    /**
     * Generated from protobuf field <code>string category = 2;</code>
     */
    protected $category = '';
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>double size = 5;</code>
     */
    protected $size = 0.0;
    /**
     * Generated from protobuf field <code>double amount = 6;</code>
     */
    protected $amount = 0.0;
    /**
     * Generated from protobuf field <code>double sweet = 7;</code>
     */
    protected $sweet = 0.0;
    /**
     * Generated from protobuf field <code>double hot = 8;</code>
     */
    protected $hot = 0.0;
    /**
     * Generated from protobuf field <code>double price = 9;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>double stock = 10;</code>
     */
    protected $stock = 0.0;
    /**
     * Generated from protobuf field <code>string imageurl = 11;</code>
     */
    protected $imageurl = '';
    /**
     * Generated from protobuf field <code>bool isavailable = 12;</code>
     */
    protected $isavailable = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $menuid
     *     @type string $category
     *     @type string $name
     *     @type string $description
     *     @type float $size
     *     @type float $amount
     *     @type float $sweet
     *     @type float $hot
     *     @type float $price
     *     @type float $stock
     *     @type string $imageurl
     *     @type bool $isavailable
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Guest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string menuid = 1;</code>
     * @return string
     */
    public function getMenuid()
    {
        return $this->menuid;
    }

    /**
     * Generated from protobuf field <code>string menuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMenuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->menuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category = 2;</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>string category = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double size = 5;</code>
     * @return float
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * Generated from protobuf field <code>double size = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkDouble($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 6;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double sweet = 7;</code>
     * @return float
     */
    public function getSweet()
    {
        return $this->sweet;
    }

    /**
     * Generated from protobuf field <code>double sweet = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setSweet($var)
    {
        GPBUtil::checkDouble($var);
        $this->sweet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double hot = 8;</code>
     * @return float
     */
    public function getHot()
    {
        return $this->hot;
    }

    /**
     * Generated from protobuf field <code>double hot = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setHot($var)
    {
        GPBUtil::checkDouble($var);
        $this->hot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price = 9;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>double price = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double stock = 10;</code>
     * @return float
     */
    public function getStock()
    {
        return $this->stock;
    }

    /**
     * Generated from protobuf field <code>double stock = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setStock($var)
    {
        GPBUtil::checkDouble($var);
        $this->stock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string imageurl = 11;</code>
     * @return string
     */
    public function getImageurl()
    {
        return $this->imageurl;
    }

    /**
     * Generated from protobuf field <code>string imageurl = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setImageurl($var)
    {
        GPBUtil::checkString($var, True);
        $this->imageurl = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isavailable = 12;</code>
     * @return bool
     */
    public function getIsavailable()
    {
        return $this->isavailable;
    }

    /**
     * Generated from protobuf field <code>bool isavailable = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsavailable($var)
    {
        GPBUtil::checkBool($var);
        $this->isavailable = $var;

        return $this;
    }

}

