<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guest.proto

namespace Guest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Guest.GuestDeleteCartList</code>
 */
class GuestDeleteCartList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string orderdetailid = 1;</code>
     */
    protected $orderdetailid = '';
    /**
     * Generated from protobuf field <code>string orderid = 2;</code>
     */
    protected $orderid = '';
    /**
     * Generated from protobuf field <code>double amount = 3;</code>
     */
    protected $amount = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $orderdetailid
     *     @type string $orderid
     *     @type float $amount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Guest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string orderdetailid = 1;</code>
     * @return string
     */
    public function getOrderdetailid()
    {
        return $this->orderdetailid;
    }

    /**
     * Generated from protobuf field <code>string orderdetailid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderdetailid($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderdetailid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string orderid = 2;</code>
     * @return string
     */
    public function getOrderid()
    {
        return $this->orderid;
    }

    /**
     * Generated from protobuf field <code>string orderid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderid($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 3;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

}

