<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guest.proto

namespace Guest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Guest.GuestSubmitAllCartList</code>
 */
class GuestSubmitAllCartList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string orderid = 1;</code>
     */
    protected $orderid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $orderid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Guest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string orderid = 1;</code>
     * @return string
     */
    public function getOrderid()
    {
        return $this->orderid;
    }

    /**
     * Generated from protobuf field <code>string orderid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderid($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderid = $var;

        return $this;
    }

}

