<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guest.proto

namespace Guest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Guest.GuestViewOrderResponse</code>
 */
class GuestViewOrderResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string status = 1;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string session = 2;</code>
     */
    protected $session = '';
    /**
     * Generated from protobuf field <code>repeated .Guest.GuestViewOrderList1 info = 3;</code>
     */
    private $info;
    /**
     * Generated from protobuf field <code>repeated .Guest.GuestViewOrderList2 detail = 4;</code>
     */
    private $detail;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $status
     *     @type string $session
     *     @type array<\Guest\GuestViewOrderList1>|\Google\Protobuf\Internal\RepeatedField $info
     *     @type array<\Guest\GuestViewOrderList2>|\Google\Protobuf\Internal\RepeatedField $detail
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Guest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string session = 2;</code>
     * @return string
     */
    public function getSession()
    {
        return $this->session;
    }

    /**
     * Generated from protobuf field <code>string session = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSession($var)
    {
        GPBUtil::checkString($var, True);
        $this->session = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Guest.GuestViewOrderList1 info = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Generated from protobuf field <code>repeated .Guest.GuestViewOrderList1 info = 3;</code>
     * @param array<\Guest\GuestViewOrderList1>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Guest\GuestViewOrderList1::class);
        $this->info = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Guest.GuestViewOrderList2 detail = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDetail()
    {
        return $this->detail;
    }

    /**
     * Generated from protobuf field <code>repeated .Guest.GuestViewOrderList2 detail = 4;</code>
     * @param array<\Guest\GuestViewOrderList2>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDetail($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Guest\GuestViewOrderList2::class);
        $this->detail = $arr;

        return $this;
    }

}

