<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guest.proto

namespace Guest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Guest.GuestViewOrderList1</code>
 */
class GuestViewOrderList1 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string table = 1;</code>
     */
    protected $table = '';
    /**
     * Generated from protobuf field <code>string customer = 2;</code>
     */
    protected $customer = '';
    /**
     * Generated from protobuf field <code>double total = 3;</code>
     */
    protected $total = 0.0;
    /**
     * Generated from protobuf field <code>double service = 4;</code>
     */
    protected $service = 0.0;
    /**
     * Generated from protobuf field <code>double tax = 5;</code>
     */
    protected $tax = 0.0;
    /**
     * Generated from protobuf field <code>double grandtotal = 6;</code>
     */
    protected $grandtotal = 0.0;
    /**
     * Generated from protobuf field <code>string orderstatus = 7;</code>
     */
    protected $orderstatus = '';
    /**
     * Generated from protobuf field <code>bool isphone = 8;</code>
     */
    protected $isphone = false;
    /**
     * Generated from protobuf field <code>double vatrate = 9;</code>
     */
    protected $vatrate = 0.0;
    /**
     * Generated from protobuf field <code>double servicerate = 10;</code>
     */
    protected $servicerate = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $table
     *     @type string $customer
     *     @type float $total
     *     @type float $service
     *     @type float $tax
     *     @type float $grandtotal
     *     @type string $orderstatus
     *     @type bool $isphone
     *     @type float $vatrate
     *     @type float $servicerate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Guest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string table = 1;</code>
     * @return string
     */
    public function getTable()
    {
        return $this->table;
    }

    /**
     * Generated from protobuf field <code>string table = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTable($var)
    {
        GPBUtil::checkString($var, True);
        $this->table = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customer = 2;</code>
     * @return string
     */
    public function getCustomer()
    {
        return $this->customer;
    }

    /**
     * Generated from protobuf field <code>string customer = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomer($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total = 3;</code>
     * @return float
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>double total = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkDouble($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double service = 4;</code>
     * @return float
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>double service = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkDouble($var);
        $this->service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double tax = 5;</code>
     * @return float
     */
    public function getTax()
    {
        return $this->tax;
    }

    /**
     * Generated from protobuf field <code>double tax = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setTax($var)
    {
        GPBUtil::checkDouble($var);
        $this->tax = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double grandtotal = 6;</code>
     * @return float
     */
    public function getGrandtotal()
    {
        return $this->grandtotal;
    }

    /**
     * Generated from protobuf field <code>double grandtotal = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setGrandtotal($var)
    {
        GPBUtil::checkDouble($var);
        $this->grandtotal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string orderstatus = 7;</code>
     * @return string
     */
    public function getOrderstatus()
    {
        return $this->orderstatus;
    }

    /**
     * Generated from protobuf field <code>string orderstatus = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setOrderstatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->orderstatus = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isphone = 8;</code>
     * @return bool
     */
    public function getIsphone()
    {
        return $this->isphone;
    }

    /**
     * Generated from protobuf field <code>bool isphone = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsphone($var)
    {
        GPBUtil::checkBool($var);
        $this->isphone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double vatrate = 9;</code>
     * @return float
     */
    public function getVatrate()
    {
        return $this->vatrate;
    }

    /**
     * Generated from protobuf field <code>double vatrate = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setVatrate($var)
    {
        GPBUtil::checkDouble($var);
        $this->vatrate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double servicerate = 10;</code>
     * @return float
     */
    public function getServicerate()
    {
        return $this->servicerate;
    }

    /**
     * Generated from protobuf field <code>double servicerate = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setServicerate($var)
    {
        GPBUtil::checkDouble($var);
        $this->servicerate = $var;

        return $this;
    }

}

