<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guest.proto

namespace Guest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Guest.GuestAddOrderList</code>
 */
class GuestAddOrderList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string menuid = 1;</code>
     */
    protected $menuid = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>double price = 3;</code>
     */
    protected $price = 0.0;
    /**
     * Generated from protobuf field <code>double amount = 4;</code>
     */
    protected $amount = 0.0;
    /**
     * Generated from protobuf field <code>double subtotal = 5;</code>
     */
    protected $subtotal = 0.0;
    /**
     * Generated from protobuf field <code>repeated string addonName = 6;</code>
     */
    private $addonName;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $menuid
     *     @type string $name
     *     @type float $price
     *     @type float $amount
     *     @type float $subtotal
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $addonName
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Guest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string menuid = 1;</code>
     * @return string
     */
    public function getMenuid()
    {
        return $this->menuid;
    }

    /**
     * Generated from protobuf field <code>string menuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMenuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->menuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price = 3;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Generated from protobuf field <code>double price = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double amount = 4;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>double amount = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkDouble($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double subtotal = 5;</code>
     * @return float
     */
    public function getSubtotal()
    {
        return $this->subtotal;
    }

    /**
     * Generated from protobuf field <code>double subtotal = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setSubtotal($var)
    {
        GPBUtil::checkDouble($var);
        $this->subtotal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string addonName = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddonName()
    {
        return $this->addonName;
    }

    /**
     * Generated from protobuf field <code>repeated string addonName = 6;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddonName($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->addonName = $arr;

        return $this;
    }

}

